language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - export BASEDIR=$(pwd)
  - echo BASEDIR ${BASEDIR}
  - pip install --user awscli
  - bash ${BASEDIR}/travis/download.sh bazelcache /private/var/tmp/_bazel_travis
  - bash ${BASEDIR}/travis/download.sh cocl ${BASEDIR}/cuda-on-cl
  - mkdir soft
  - cd soft
  - echo ========= swig ============
  - bash ${BASEDIR}/travis/build-swig.sh
  - ls -lh /usr/local/bin/swig
  - echo =============== bazel =====================
  - bash ${BASEDIR}/travis/install-bazel.sh
  - export PATH=$HOME/bin:$PATH
  - bazel --batch version
  - echo ====== python ==============
  - cd ${BASEDIR}
  - bash ${BASEDIR}/travis/install-python.sh
  - echo ================ tensorflow configure ==================
  - cd ${BASEDIR}
  - bash ${BASEDIR}/travis/run-configure.sh
  - echo =========== clang ================================
  - cd ${BASEDIR}
  - CLANG_VERSION=3.8.0
  - time wget http://llvm.org/releases/${CLANG_VERSION}/clang+llvm-${CLANG_VERSION}-x86_64-apple-darwin.tar.xz
  - time tar -xf clang+llvm-${CLANG_VERSION}-x86_64-apple-darwin.tar.xz
  - ls
  - export CLANG_HOME=${PWD}/clang+llvm-${CLANG_VERSION}-x86_64-apple-darwin
  - cd ${BASEDIR}
  - git submodule update --init --recursive
  - echo ============= cuda-on-cl ================
  - cd third_party/cuda-on-cl
  - mkdir build
  - cd build
  - echo CLANG_HOME ${CLANG_HOME}
  - cmake .. -DCLANG_HOME=${CLANG_HOME} -DBUILD_TESTS=ON -DTESTS_DUMP_CL=ON
  - make -j 8
  - make install
  - bash ${BASEDIR}/travis/upload.sh cocl ${BASEDIR}/cuda-on-cl
  - echo ========= tensorflow install =================
  - cd ${BASEDIR}
  - export PATH=$HOME/bin:$PATH
  - bazel --batch version
  - time bazel --batch build --verbose_failures --copt="-ferror-limit=500" //tensorflow/core:ops
  - bash ${BASEDIR}/travis/upload.sh bazelcache /private/var/tmp/_bazel_travis
  - time bazel --batch build --verbose_failures --copt="-ferror-limit=500" //tensorflow/core:framework
  - bash ${BASEDIR}/travis/upload.sh bazelcache /private/var/tmp/_bazel_travis
  - time bazel --batch build --verbose_failures --copt="-ferror-limit=500" //tensorflow/core:lib
  - bash ${BASEDIR}/travis/upload.sh bazelcache /private/var/tmp/_bazel_travis
  - bazel --batch build --verbose_failures --copt="-ferror-limit=500" //tensorflow/tools/pip_package:build_pip_package
  - bash ${BASEDIR}/travis/upload.sh bazelcache /private/var/tmp/_bazel_travis
  - bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflowpkg

script:
  - cd ${BASEDIR}

notifications:
  email:
    on_success: never
    on_failure: never
