language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - export BASEDIR=$(pwd)
  - echo BASEDIR ${BASEDIR}
  - git submodule update --init --recursive
  - pip install --user awscli
  - bash ${BASEDIR}/travis/download.sh bazelinstall /private/var/tmp/_bazel_travis
  - bash ${BASEDIR}/travis/download.sh cocl2 ${BASEDIR}/third_party/cuda-on-cl
  - mkdir soft
  - cd soft
  - echo ========= swig ============
  - bash ${BASEDIR}/travis/build-swig.sh
  - ls -lh /usr/local/bin/swig
  - echo =============== bazel =====================
  - bash ${BASEDIR}/travis/install-bazel.sh
  - export PATH=$HOME/bin:$PATH
  - echo ====== python ==============
  - cd ${BASEDIR}
  - bash ${BASEDIR}/travis/install-python.sh
  - echo ================ tensorflow configure ==================
  - cd ${BASEDIR}
  # - bash ${BASEDIR}/travis/download.sh bazelinstall /private/var/tmp/_bazel_travis
  - START=`python ${BASEDIR}/travis/seconds.py`
  - bash ${BASEDIR}/travis/run-configure.sh
  - END=`python ${BASEDIR}/travis/seconds.py`
  - DIFF=`echo "$END - $START" | bc -l`
  - echo DIFF $DIFF
  - if [ `echo "${DIFF} > 60" | bc -l` -eq 1 ]; then { bash ${BASEDIR}/travis/upload.sh bazelinstall /private/var/tmp/_bazel_travis; } fi
  - echo =========== clang ================================
  - cd ${BASEDIR}
  - CLANG_VERSION=3.8.0
  - time wget http://llvm.org/releases/${CLANG_VERSION}/clang+llvm-${CLANG_VERSION}-x86_64-apple-darwin.tar.xz
  - time tar -xf clang+llvm-${CLANG_VERSION}-x86_64-apple-darwin.tar.xz
  - ls
  - export CLANG_HOME=${PWD}/clang+llvm-${CLANG_VERSION}-x86_64-apple-darwin
  - cd ${BASEDIR}
  - echo ============= cuda-on-cl ================
  - cd ${BASEDIR}/third_party/cuda-on-cl
  - mkdir -p build
  - cd build
  - echo CLANG_HOME ${CLANG_HOME}
  - cmake .. -DCLANG_HOME=${CLANG_HOME} -DBUILD_TESTS=ON -DTESTS_DUMP_CL=ON
  - START=`python ${BASEDIR}/travis/seconds.py`
  - time make -j 8
  - END=`python ${BASEDIR}/travis/seconds.py`
  - DIFF=`echo "$END - $START" | bc -l`
  - echo DIFF $DIFF
  - make install
  - if [ `echo "${DIFF} > 60" | bc -l` -eq 1 ]; then { bash ${BASEDIR}/travis/upload.sh cocl2 ${BASEDIR}/third_party/cuda-on-cl; } fi
  - echo ========= tensorflow install =================
  - cd ${BASEDIR}
  - export PATH=$HOME/bin:$PATH
  - bash ${BASEDIR}/travis/download.sh bazel1 /private/var/tmp/_bazel_travis
  - START=`python ${BASEDIR}/travis/seconds.py`
  # this is about 8 minutes:
  - time bazel --batch build --verbose_failures --copt="-ferror-limit=500" //tensorflow/core:ops
  - END=`python ${BASEDIR}/travis/seconds.py`
  - DIFF=`echo "$END - $START" | bc -l`
  - echo DIFF $DIFF
  - if [ `echo "${DIFF} > 60" | bc -l` -eq 1 ]; then { bash ${BASEDIR}/travis/upload.sh bazel1 /private/var/tmp/_bazel_travis install; } fi

  # this does nothing :-P :
  #- time bazel --batch build --verbose_failures --copt="-ferror-limit=500" //tensorflow/core:framework
  #- bash ${BASEDIR}/travis/download.sh bazelcache /private/var/tmp/_bazel_travis
  # doesnt do much either :-P
  #- time bazel --batch build --verbose_failures --copt="-ferror-limit=500" //tensorflow/core:lib
  #- bash ${BASEDIR}/travis/upload.sh bazelcache /private/var/tmp/_bazel_travis

  # about 1 minute, not really worth it...
  #- bash ${BASEDIR}/travis/download.sh bazel2 /private/var/tmp/_bazel_travis
  #- time bazel --batch build --verbose_failures --copt="-ferror-limit=500" //tensorflow/stream_executor:stream_executor
  #- bash ${BASEDIR}/travis/upload.sh bazel2 /private/var/tmp/_bazel_travis

  - bash ${BASEDIR}/travis/download.sh bazel3 /private/var/tmp/_bazel_travis
  - START=`python ${BASEDIR}/travis/seconds.py`
  - time bazel --batch build --verbose_failures --copt="-ferror-limit=500" //tensorflow/core:framework //tensorflow/core:lib //tensorflow/stream_executor:stream_executor //tensorflow/core:gpu_runtime
  - END=`python ${BASEDIR}/travis/seconds.py`
  - DIFF=`echo "$END - $START" | bc -l`
  - echo DIFF $DIFF
  - if [ `echo "${DIFF} > 60" | bc -l` -eq 1 ]; then { bash ${BASEDIR}/travis/upload.sh bazel3 /private/var/tmp/_bazel_travis install; } fi

  - bash ${BASEDIR}/travis/download.sh bazel4aa /private/var/tmp/_bazel_travis
  - START=`python ${BASEDIR}/travis/seconds.py`
  - time bazel --batch build --verbose_failures //tensorflow/core/kernels:array
  - END=`python ${BASEDIR}/travis/seconds.py`
  - DIFF=`echo "$END - $START" | bc -l`
  - echo DIFF $DIFF
  - if [ `echo "${DIFF} > 60" | bc -l` -eq 1 ]; then { bash ${BASEDIR}/travis/upload.sh bazel4aa /private/var/tmp/_bazel_travis install; } fi

  # 13 seconds.  pointless
  #- bash ${BASEDIR}/travis/download.sh bazel4 /private/var/tmp/_bazel_travis
  #- time bazel --batch build --verbose_failures --copt="-ferror-limit=500" //tensorflow/core:gpu_lib
  #- bash ${BASEDIR}/travis/upload.sh bazel4 /private/var/tmp/_bazel_travis

  - bash ${BASEDIR}/travis/download.sh bazel4a /private/var/tmp/_bazel_travis
  - START=`python ${BASEDIR}/travis/seconds.py`
  - for KERNEL in array candidate_sampler_ops control_flow_ops ctc_ops data_flow function_ops image io linalg logging math; do { echo "building //tensorflow/core/kernels:${KERNEL}"; time bazel build --verbose_failures //tensorflow/core/kernels:${KERNEL}; } done
  - bazel shutdown
  - END=`python ${BASEDIR}/travis/seconds.py`
  - DIFF=`echo "$END - $START" | bc -l`
  - echo DIFF $DIFF
  - if [ `echo "${DIFF} > 90" | bc -l` -eq 1 ]; then { bash ${BASEDIR}/travis/upload.sh bazel4a /private/var/tmp/_bazel_travis install; } fi

  - bash ${BASEDIR}/travis/download.sh bazel4b1 /private/var/tmp/_bazel_travis
  - START=`python ${BASEDIR}/travis/seconds.py`
  - for KERNEL in multinomial_op nn parameterized_truncated_normal_op parsing random_ops required; do { echo "building //tensorflow/core/kernels:${KERNEL}"; time bazel build --verbose_failures //tensorflow/core/kernels:${KERNEL}; } done
  - bazel shutdown
  - END=`python ${BASEDIR}/travis/seconds.py`
  - DIFF=`echo "$END - $START" | bc -l`
  - echo DIFF $DIFF
  - if [ `echo "${DIFF} > 90" | bc -l` -eq 1 ]; then { bash ${BASEDIR}/travis/upload.sh bazel4b1 /private/var/tmp/_bazel_travis install; } fi

  - bash ${BASEDIR}/travis/download.sh bazel4b2 /private/var/tmp/_bazel_travis
  - START=`python ${BASEDIR}/travis/seconds.py`
  - for KERNEL in sdca_ops sparse state string training_ops; do { echo "building //tensorflow/core/kernels:${KERNEL}"; time bazel build --verbose_failures //tensorflow/core/kernels:${KERNEL}; } done
  - bazel shutdown
  - END=`python ${BASEDIR}/travis/seconds.py`
  - DIFF=`echo "$END - $START" | bc -l`
  - echo DIFF $DIFF
  - if [ `echo "${DIFF} > 90" | bc -l` -eq 1 ]; then { bash ${BASEDIR}/travis/upload.sh bazel4b2 /private/var/tmp/_bazel_travis install; } fi

  - bash ${BASEDIR}/travis/download.sh bazel4b3 /private/var/tmp/_bazel_travis
  - START=`python ${BASEDIR}/travis/seconds.py`
  - for KERNEL in fact_op array_not_windows math_not_windows; do { echo "building //tensorflow/core/kernels:${KERNEL}"; time bazel build --verbose_failures //tensorflow/core/kernels:${KERNEL}; } done
  - bazel shutdown
  - END=`python ${BASEDIR}/travis/seconds.py`
  - DIFF=`echo "$END - $START" | bc -l`
  - echo DIFF $DIFF
  - if [ `echo "${DIFF} > 90" | bc -l` -eq 1 ]; then { bash ${BASEDIR}/travis/upload.sh bazel4b3 /private/var/tmp/_bazel_travis install; } fi

  - bash ${BASEDIR}/travis/download.sh bazel4b /private/var/tmp/_bazel_travis
  - START=`python ${BASEDIR}/travis/seconds.py`
  - time bazel --batch build --verbose_failures --copt="-ferror-limit=500" //tensorflow/core:all_kernels
  - END=`python ${BASEDIR}/travis/seconds.py`
  - DIFF=`echo "$END - $START" | bc -l`
  - echo DIFF $DIFF
  - if [ `echo "${DIFF} > 90" | bc -l` -eq 1 ]; then { bash ${BASEDIR}/travis/upload.sh bazel4b /private/var/tmp/_bazel_travis install; } fi

  - bash ${BASEDIR}/travis/download.sh bazel5 /private/var/tmp/_bazel_travis
  - START=`python ${BASEDIR}/travis/seconds.py`
  - bazel --batch build --verbose_failures --copt="-ferror-limit=500" //tensorflow/tools/pip_package:build_pip_package
  - END=`python ${BASEDIR}/travis/seconds.py`
  - DIFF=`echo "$END - $START" | bc -l`
  - echo DIFF $DIFF
  - if [ `echo "${DIFF} > 90" | bc -l` -eq 1 ]; then { bash ${BASEDIR}/travis/upload.sh bazel5 /private/var/tmp/_bazel_travis install; } fi

  - bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflowpkg

script:
  - cd ${BASEDIR}

notifications:
  email:
    on_success: never
    on_failure: never
